// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PerformansSitesi.Infrastructure.Data;

#nullable disable

namespace PerformansSitesi.Migrations
{
    [DbContext(typeof(PerformansDbContext))]
    [Migration("20260117202532_AddToplamPuan")]
    partial class AddToplamPuan
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Degerlendirme", b =>
                {
                    b.Property<int>("DegerlendirmeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DegerlendirmeId"));

                    b.Property<int>("DonemId")
                        .HasColumnType("int");

                    b.Property<int>("Durum")
                        .HasColumnType("int");

                    b.Property<string>("GelisimOnerileri")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GelisimeAcikYonler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenelSonuc")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("GucluYonler")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("datetime2");

                    b.Property<int>("NihaiYoneticiId")
                        .HasColumnType("int");

                    b.Property<string>("NihaiYoneticiNotu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OlusturmaTarihi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<decimal?>("OrtalamaPuan")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.Property<int>("Yonetici1Id")
                        .HasColumnType("int");

                    b.Property<string>("Yonetici1Notu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Yonetici2Id")
                        .HasColumnType("int");

                    b.Property<string>("Yonetici2Notu")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DegerlendirmeId");

                    b.HasIndex("PersonelId");

                    b.HasIndex("DonemId", "PersonelId")
                        .IsUnique();

                    b.ToTable("Degerlendirmeler");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.DegerlendirmeDetay", b =>
                {
                    b.Property<int>("DetayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DetayId"));

                    b.Property<int>("DegerlendirmeId")
                        .HasColumnType("int");

                    b.Property<string>("NihaiYoneticiYorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SoruId")
                        .HasColumnType("int");

                    b.Property<int?>("Yonetici1Puan")
                        .HasColumnType("int");

                    b.Property<string>("Yonetici1Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Yonetici2Yorum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DetayId");

                    b.HasIndex("SoruId");

                    b.HasIndex("DegerlendirmeId", "SoruId")
                        .IsUnique();

                    b.ToTable("DegerlendirmeDetaylari");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Donem", b =>
                {
                    b.Property<int>("DonemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonemId"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<bool>("AktifMi")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("BaslangicTarihi")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("BitisTarihi")
                        .HasColumnType("datetime2");

                    b.HasKey("DonemId");

                    b.ToTable("Donemler");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Kullanici", b =>
                {
                    b.Property<int>("KullaniciId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KullaniciId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PersonelId")
                        .HasColumnType("int");

                    b.Property<int>("Rol")
                        .HasColumnType("int");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KullaniciId");

                    b.HasIndex("KullaniciAdi")
                        .IsUnique();

                    b.HasIndex("PersonelId");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.PerformansSorusu", b =>
                {
                    b.Property<int>("SoruId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SoruId"));

                    b.Property<int>("SablonId")
                        .HasColumnType("int");

                    b.Property<int>("SiraNo")
                        .HasColumnType("int");

                    b.Property<string>("SoruMetni")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("ZorunluMu")
                        .HasColumnType("bit");

                    b.HasKey("SoruId");

                    b.HasIndex("SablonId", "SiraNo");

                    b.ToTable("PerformansSorulari");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Personel", b =>
                {
                    b.Property<int>("PersonelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonelId"));

                    b.Property<string>("AdSoyad")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Departman")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Gorev")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Mudurluk")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("NihaiYoneticiId")
                        .HasColumnType("int");

                    b.Property<string>("ProjeAdi")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("SicilNo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Yonetici1Id")
                        .HasColumnType("int");

                    b.Property<int>("Yonetici2Id")
                        .HasColumnType("int");

                    b.HasKey("PersonelId");

                    b.HasIndex("NihaiYoneticiId");

                    b.HasIndex("SicilNo")
                        .IsUnique();

                    b.HasIndex("Yonetici1Id");

                    b.HasIndex("Yonetici2Id");

                    b.ToTable("Personeller");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Degerlendirme", b =>
                {
                    b.HasOne("PerformansSitesi.Domain.Entities.Donem", "Donem")
                        .WithMany()
                        .HasForeignKey("DonemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformansSitesi.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Donem");

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.DegerlendirmeDetay", b =>
                {
                    b.HasOne("PerformansSitesi.Domain.Entities.Degerlendirme", "Degerlendirme")
                        .WithMany("Detaylar")
                        .HasForeignKey("DegerlendirmeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PerformansSitesi.Domain.Entities.PerformansSorusu", "Soru")
                        .WithMany()
                        .HasForeignKey("SoruId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Degerlendirme");

                    b.Navigation("Soru");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Kullanici", b =>
                {
                    b.HasOne("PerformansSitesi.Domain.Entities.Personel", "Personel")
                        .WithMany()
                        .HasForeignKey("PersonelId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Personel");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Personel", b =>
                {
                    b.HasOne("PerformansSitesi.Domain.Entities.Kullanici", "NihaiYonetici")
                        .WithMany()
                        .HasForeignKey("NihaiYoneticiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformansSitesi.Domain.Entities.Kullanici", "Yonetici1")
                        .WithMany()
                        .HasForeignKey("Yonetici1Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PerformansSitesi.Domain.Entities.Kullanici", "Yonetici2")
                        .WithMany()
                        .HasForeignKey("Yonetici2Id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NihaiYonetici");

                    b.Navigation("Yonetici1");

                    b.Navigation("Yonetici2");
                });

            modelBuilder.Entity("PerformansSitesi.Domain.Entities.Degerlendirme", b =>
                {
                    b.Navigation("Detaylar");
                });
#pragma warning restore 612, 618
        }
    }
}
